name: exceRNApipeline
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - biopython=1.76
  - fastqc=0.11.9
  - htseq=0.11.3
  - htstream=1.2.0
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - pandas=1.0.2
  - pathos=0.2.5
  - python=3.7.3
  - python-magic=0.4.15
  - samtools=1.10
  - seaborn=0.10.0
  - snakemake=5.10.0
  - swig=4.0.1
  - star=2.7.3a
