samples:
    SRR8114380: "../input/SRR8114380/SRR8114380_1.fastq.gz"
    SRR8114381: "../input/SRR8114381/SRR8114381_1.fastq.gz"
    SRR8114382: "../input/SRR8114382/SRR8114382_1.fastq.gz"
    SRR8114383: "../input/SRR8114383/SRR8114383_1.fastq.gz"
    SRR8114384: "../input/SRR8114384/SRR8114384_1.fastq.gz"
    SRR8114385: "../input/SRR8114385/SRR8114385_1.fastq.gz"

adapter: "TGGAATTCTCGGGTGCCAAGGAACTC"

exogenous_mapping: true

# Set it to false if your HPC does not use scratch
use_scratch: true

silva_split: 10

bacteria_split: 20

rRNA: "genomes/U13369.1.fasta"