__default__:
    job-name: "SM.{rule}"
    nodes: 1
    time: "1-00:00:00"
    mem: '2G'
    mem-per-cpu: "2G"
    partition: "med"
    exclude: "c8-96"
    output: "slurmout/SM_{rule}_%A.log"
    error: "slurmout/SM_{rule}_%A.err"
    mail-user: "$USER_EMAIL"
    mail-type: "FAIL"
    exclude: "''"

genome_index:
    mem: 60G

genome_mapping:
    mem: 60G

make_re_fasta:
    mem: 60G

re_index:
    mem: 60G

re_mapping:
    mem: 60G

silva_index:
    mem: 30G

silva_mapping:
    mem: 30G

bacteria_index:
    mem: 44G

bacteria_mapping:
    mem: 60G