__default__:
    job-name: "SM.{rule}"
    nodes: 1
    time: "1-00:00:00"
    mem: '2G'
    mem-per-cpu: "2G"
    partition: "med"
    exclude: "c8-96"
    output: "slurmout/SM_{rule}_%A.log"
    error: "slurmout/SM_{rule}_%A.err"
    mail-user: "$USER_EMAIL"
    mail-type: "END,FAIL"
    exclude: "''"

preprocess:
    exclude: "c8-96"

univec_index:
    exclude: "c8-96"

univec_mapping:
    exclude: "c8-96"

rrna_index:
    exclude: "c8-96"

rrna_mapping:
    exclude: "c8-96"

genome_index:
    exclude: "c8-96"
    mem: 50G

genome_mapping:
    exclude: "c8-96"
    mem: 60G
