#ifndef _NCBI_TAXONOMY_RANKS_HPP_
#define _NCBI_TAXONOMY_RANKS_HPP_

#include <unordered_map>
#include <string>

const std::unordered_map<std::string, int> _NCBI_TAXONOMY_RANKS_ ({
    {"root", 0},
    {"domain", 1},
    {"subdomain", 2},
    {"realm", 3},
    {"subrealm", 4},
    {"hyperkingdom", 5},
    {"superkingdom", 6},
    {"kingdom", 7},
    {"subkingdom", 8},
    {"infrakingdom", 9},
    {"parvkingdom", 10},
    {"superphylum", 11},
    {"phylum", 12},
    {"subphylum", 13},
    {"infraphylum", 14},
    {"microphylum", 15},
    {"superclass", 16},
    {"class", 17},
    {"subclass", 18},
    {"infraclass", 19},
    {"parvclass", 20},
    {"superdivision", 21},
    {"division", 22},
    {"subdivision", 23},
    {"infradivision", 24},
    {"superlegion", 25},
    {"legion", 26},
    {"sublegion", 27},
    {"infralegion", 28},
    {"supercohort", 29},
    {"cohort", 30},
    {"subcohort", 31},
    {"infracohort", 32},
    {"gigaorder", 33},
    {"magnorder", 34},
    {"grandorder", 35},
    {"mirorder", 36},
    {"superorder", 37},
    {"series", 68},
    {"order", 39},
    {"parvorder", 46},
    {"nanorder", 41},
    {"hypoorder", 42},
    {"minorder", 43},
    {"suborder", 44},
    {"infraorder", 45},
    {"section", 66},
    {"subsection", 67},
    {"gigafamily", 49},
    {"megafamily", 50},
    {"grandfamily", 51},
    {"hyperfamily", 52},
    {"superfamily", 53},
    {"epifamily", 54},
    {"group", 56},
    {"family", 57},
    {"subfamily", 58},
    {"infrafamily", 59},
    {"supertribe", 60},
    {"tribe", 61},
    {"subtribe", 62},
    {"infratribe", 63},
    {"genus", 64},
    {"subgenus", 65},
    {"subseries", 69},
    {"superspecies", 70},
    {"species group", 70},
    {"species subgroup", 71},
    {"species", 72},
    {"subspecies", 73},
    {"variety", 74},
    {"varietas", 74},
    {"subvariety", 75},
    {"form", 76},
    {"forma", 76},
    {"subform", 77},
    {"no rank", 999}
});

#endif